app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: '/'
user_home:
    path: '/profile'
admin_home:
    path: '/admin'

login:
    path: '/login'
register:
    path: '/register'