app:
    resource: '@AppBundle/Controller/'
    type: annotation

homepage:
    path: '/'
    defaults: { _controller: AppBundle:Default:index }
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"

app_courses:
    resource: "@AppBundle/Resources/config/routing/course.yml"
    prefix: /course

app_lectures:
    resource: "@AppBundle/Resources/config/routing/lecture.yml"
    prefix:   /lecture

app_stats:
    resource: "@AppBundle/Resources/config/routing/stats.yml"
    prefix: /stats

login:
    path: '/login'
register:
    path: '/register'
change_passwd:
    path: '/profile/change-password'